version: "3.7"
services:

  prom-docker-limit-exporter:
    image: sachinnicky/prom-docker-limit-exporter:latest
    # environment:
    ports:
      - "8080"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - type: bind
        source: ./infra/prometheus.yaml
        target: /etc/prometheus.yaml
    entrypoint:
      - /bin/prometheus
      - --config.file=/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./infra/datasources:/etc/grafana/provisioning/datasources
      - ./infra/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./infra/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
