global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'prom-docker-limit-exporter'
    static_configs:
    - targets: ['prom-docker-limit-exporter:8080']
